Fixes #553 - Don't load Form data
sartography/cr-connect-workflow pull request #429
Opened 2021-12-01 21:12 UTC by Leashys

adds an extension so that you can opt to clear out form data on a given task

2021-12-03 15:04 UTC, cullerton commented
This should have a test.

2021-12-03 17:24 UTC, Leashys commented
ok i wrote a test

2021-12-07 14:16 UTC, Leashys commented
@danfunk  this is ready to merge in now BTW well if you like that test it is

2021-12-07 14:43 UTC, danfunk requested changes

2021-12-07 14:43 UTC, danfunk commented on crc/services/workflow_service.py
> +        if task.properties and "clear_data" in task.properties:
@Leashys - this won't work for Alex's case that he described this morning.  
What we need to do is /prevent/ the previously submitted form data from overwriting what he has set in a previous step.

2021-12-07 14:43 UTC, danfunk commented on crc/services/workflow_service.py
> +        if task.properties and "clear_data" in task.properties:
a good test for this is
Task 1:  Have a radio button for "a", "b", "c"
Task 2: Display a text box that contains the value selected on the previous page.
Task 3: End Task

It should be possible to change the value in Task 1, and have that change reflected in task 2.

2021-12-08 15:32 UTC, Leashys commented
@danfunk @danfunk @danfunk

2021-12-08 15:37 UTC, merged